apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.name}}
  name: {{ .Values.name}}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.name}}
    spec:
      containers:
        - name: {{ .Chart.Name}}
          image: {{ .Values.repo }}
          ports:
            - name: http
              containerPort: {{ .Values.port | default 80 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{ if (.Values.env) }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- end }}
