apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.name}}
  name: {{ .Values.name}}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-default-https@kubernetescrd
spec:
  rules:
  - host: "{{ .Values.name}}.llevi.hu"
    http:
      paths:
      - backend:
          service:
            name: "{{ .Values.name}}"
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - "{{ .Values.name}}.llevi.hu"
    secretName: "{{ .Values.name}}.llevi.hu-tls"
