apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.name }}
